# ======================================= Learning configs ==================================
n_epoch: 200
batch_size: 32
test_batch_size: 16
lr: 0.0001
loss_weights: 0.5
clip_gradient: 0.1
start_epoch: 0
weight_decay: 5e-4

  # ======================================= Print and snapshot configs ==================================
snapshot_pref: ./Exps_789/fix_data_622_fix_modal_0.5_av-simil_consistent_product/
print_freq: 1
eval_freq: 1


